/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

import connecthub.entities.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Mahinour Mohamed
 */
public class GroupsManagement extends javax.swing.JFrame {

    /**
     * Creates new form GroupsManagement
     */
    User user;
    public GroupsManagement(User user) {
        initComponents();
        this.user=user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupsList = new javax.swing.JToggleButton();
        createGroup = new javax.swing.JToggleButton();
        groupSuggestions = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Groups");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        groupsList.setBackground(new java.awt.Color(0, 51, 102));
        groupsList.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        groupsList.setForeground(new java.awt.Color(255, 255, 255));
        groupsList.setText("Groups list");
        groupsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupsListActionPerformed(evt);
            }
        });

        createGroup.setBackground(new java.awt.Color(0, 51, 102));
        createGroup.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        createGroup.setForeground(new java.awt.Color(255, 255, 255));
        createGroup.setText("Create Group");
        createGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createGroupActionPerformed(evt);
            }
        });

        groupSuggestions.setBackground(new java.awt.Color(0, 51, 102));
        groupSuggestions.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        groupSuggestions.setForeground(new java.awt.Color(255, 255, 255));
        groupSuggestions.setText("Groups Suggestions");
        groupSuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupSuggestionsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(createGroup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupsList, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addComponent(groupSuggestions, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(groupsList)
                .addGap(42, 42, 42)
                .addComponent(createGroup)
                .addGap(41, 41, 41)
                .addComponent(groupSuggestions)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void groupsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupsListActionPerformed
           if (user == null) {
            JOptionPane.showMessageDialog(this,
                    "User or profile data is missing. Please log in again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            GroupsList group = new GroupsList(user,this);
            group.setVisible(true);
            group.setLocationRelativeTo(null);
            setVisible(false);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_groupsListActionPerformed

    private void createGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createGroupActionPerformed
        if (user == null) {
            JOptionPane.showMessageDialog(this,
                    "User or profile data is missing. Please log in again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            CreateGroup createGroup = new CreateGroup(user,this);
            createGroup.setVisible(true);
            createGroup.setLocationRelativeTo(null);
            setVisible(false);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_createGroupActionPerformed

    private void groupSuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupSuggestionsActionPerformed
        if (user == null) {
            JOptionPane.showMessageDialog(this,
                    "User or profile data is missing. Please log in again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            GroupSuggestion groupSuggestion = new GroupSuggestion(user,this);
            groupSuggestion.setVisible(true);
            groupSuggestion.setLocationRelativeTo(null);
            setVisible(false);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(null, "ERROR", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_groupSuggestionsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (user == null) {
            JOptionPane.showMessageDialog(this,
                    "User or Newsfeed data is missing. Please log in again.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {

            FrontProfile f = FrontProfile.getInstanceOf();
            f.setVisible(true);
            f.setLocationRelativeTo(null);
            setVisible(false);
        } catch (Exception e) {

        }
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton createGroup;
    private javax.swing.JToggleButton groupSuggestions;
    private javax.swing.JToggleButton groupsList;
    // End of variables declaration//GEN-END:variables
}
