/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend;

/**
 *
 * @author Mahinour Mohamed
 */
public class Newsfeed extends javax.swing.JFrame {

    /**
     * Creates new form Newsfeed
     */
    public Newsfeed() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        refresh = new javax.swing.JToggleButton();
        friendsNewsfeed = new javax.swing.JToggleButton();
        story = new javax.swing.JToggleButton();
        friendsSuggestions = new javax.swing.JToggleButton();
        post = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Newsfeed");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(0, 51, 102));
        refresh.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        friendsNewsfeed.setBackground(new java.awt.Color(0, 51, 102));
        friendsNewsfeed.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        friendsNewsfeed.setForeground(new java.awt.Color(255, 255, 255));
        friendsNewsfeed.setText("Friends newsFeed");
        friendsNewsfeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsNewsfeedActionPerformed(evt);
            }
        });

        story.setBackground(new java.awt.Color(0, 51, 102));
        story.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        story.setForeground(new java.awt.Color(255, 255, 255));
        story.setText("Add story");
        story.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storyActionPerformed(evt);
            }
        });

        friendsSuggestions.setBackground(new java.awt.Color(0, 51, 102));
        friendsSuggestions.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        friendsSuggestions.setForeground(new java.awt.Color(255, 255, 255));
        friendsSuggestions.setText("Friends Suggestions");
        friendsSuggestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsSuggestionsActionPerformed(evt);
            }
        });

        post.setBackground(new java.awt.Color(0, 51, 102));
        post.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        post.setForeground(new java.awt.Color(255, 255, 255));
        post.setText("Create new post");
        post.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(friendsSuggestions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(friendsNewsfeed, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(story, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(post, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(refresh)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(post)
                .addGap(18, 18, 18)
                .addComponent(story)
                .addGap(18, 18, 18)
                .addComponent(friendsNewsfeed)
                .addGap(18, 18, 18)
                .addComponent(friendsSuggestions)
                .addGap(18, 18, 18)
                .addComponent(refresh)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void friendsNewsfeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsNewsfeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friendsNewsfeedActionPerformed

    private void postActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postActionPerformed

    private void storyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_storyActionPerformed

    private void friendsSuggestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsSuggestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_friendsSuggestionsActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton friendsNewsfeed;
    private javax.swing.JToggleButton friendsSuggestions;
    private javax.swing.JToggleButton post;
    private javax.swing.JToggleButton refresh;
    private javax.swing.JToggleButton story;
    // End of variables declaration//GEN-END:variables
}
